version: '3'

services:
  camo:
    env_file: .env
    container_name: camo
    image: inventid/camo
    labels:
      - traefik.enable=true
      - traefik.port=8000
      - traefik.frontend.rule=Host:camo.csvalpha.nl
